name: build-plugin
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        webpack: [4]
        html-webpack: [4, 3]
        include:
          - webpack: 5
            html-webpack: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.webpack < 5 && '16.20.2' || '20.8.0' }}
      - run: npm install
      - run: npm install -D webpack@${{ matrix.webpack }} html-webpack-plugin@${{ matrix.html-webpack }}
      - run: npm run test
      - run: npm run build
